---
- name: Running Config Backup
  hosts: R1
  gather_facts: false
  connection: local

  tasks:
    - name: Display Running Config
      ios_command:
        commands:
          - show running-config
      register: config

    - name: Saving Output
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "backup/backupconfig{{ inventory_hostname }}.txt"